
services:
  gnb:
    image: fgftk/gnb-ueransim:${UERANSIM_VERSION}
    container_name: gnb
    networks:
      - open5gs
    volumes:
      - ../../../configs/basic/ueransim/gnb.yaml:/UERANSIM/config/gnb.yaml:ro
    command: ["-c", "/UERANSIM/config/gnb.yaml"]

  ue:
    image: fgftk/ue-ueransim:${UERANSIM_VERSION}
    container_name: ue
    depends_on:
      - gnb
    networks:
      - open5gs
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ../../../configs/basic/ueransim/ue.yaml:/UERANSIM/config/ue.yaml:ro
    command: ["-c", "/UERANSIM/config/ue.yaml"]

networks:
  open5gs:
    external: true

